### ISSUE TITLE
Unknown value

### ISSUE THREAD

**Issue by ghost** [thelucifermorningstar/SMLoadr-AUX#10]
.

**Comment by DjUnknown** [comment]
I have managed to know why it does not work, it is because of the download folder, the name of my folder contains two words.

**Comment by theelectricsoul** [comment]
Submit this to the SMLoadr developers :)

**Comment by DjUnknown** [comment]
Do not have teknik account, that page has closed the register, only allow registrations by invitation, i have solved by putting a single word to my folder.

**Comment by theelectricsoul** [comment]
sure...  just go to theier telegram group...   if you have telegram. otherwise I'll submit

**Comment by DjUnknown** [comment]
Do not bother, it's a small thing and of easy solution, It is not of SMLoadrDev problem, this command works for me.
SMLoadr-win-x64.exe -q "MP3_320" -p "Deezer Albums/" "https://www.deezer.com/en/album/11898198"

**Comment by thelucifermorningstar** [comment]
@theelectricsoul  the application works for you?

**Comment by thelucifermorningstar** [comment]
![image](https://user-images.githubusercontent.com/37758237/38093938-d026cf48-3342-11e8-8952-c436d2cdda1e.png)

**Comment by thelucifermorningstar** [comment]
![image](https://user-images.githubusercontent.com/37758237/38094218-9656bafc-3343-11e8-9a3a-3a4a6eb26185.png)

**Comment by theelectricsoul** [comment]
No I cannot use a download folder which contains a whitespace. But it works if I use the command line directly like @DjUnknown mentioned.
