### ISSUE TITLE
[REQUEST+Issue] Don't force to use the next version

### ISSUE THREAD

**Issue by mehti1367** [thelucifermorningstar/SMLoadr-AUX#14]
Hey, I'm on a Virtual Machine (Windows Server 2012), The old version worked for me without problems But since I had to use the next version this caused problems to me, The current version seems to be not compatible with my VPS, GUI does not run at all : https://i.imgur.com/jlbz0Gw.png
I cant Download All Link with text file gives a function error : 
https://i.imgur.com/zEkzydq.png

**Comment by thelucifermorningstar** [comment]
Thanks for the feedback. I'll try to solve this

**Comment by mehti1367** [comment]
also download speed is too slow for FLAC in new version
