### ISSUE TITLE
Fully stream tracks?

### ISSUE THREAD

**Issue by mvxs** [thelucifermorningstar/SMLoadr-AUX#15]
A feature request for an ability to fully stream tracks. Preferably with a seekbar and a volume bar.

Also, there is no way to pause the preview now. ▶️ button should probably change to ❚❚ once the track starts playing, because it won't turn off.

**Comment by DooMl** [comment]
I second this, making tracks available to stream and replace will obviously make this my default music player.

**Comment by bascurtiz** [comment]
@mvxs 
@irockdude554 
@doomlerd 
Not possible.
