### ISSUE TITLE
A couple suggestions

### ISSUE THREAD

**Issue by camartinez1229** [thelucifermorningstar/SMLoadr-AUX#18]
1. Whenever I start a download, a new command window opens. Would it be possible to re-use the same command window every time instead? That way I'd have less clutter on the screen when I want to download multiple tracks or albums.
2. If you can implement the above, then can you let the command window stay open at the end of downloading, so I could inspect for any download errors? Or write to a log file? Few things annoy me more than finding out a song got skipped or didn't download correctly.
3. Or, instead of 2, I'd love to defer the downloads into a list, such as the downloadLinks.txt that SMLoadr supports. That way, I could use the AUX program to build the list of what I want to download, and then use SMLoadr to download the list in one batch.

EDIT:
I almost forgotten one other suggestion.

4. I'd love to be able to select more than one track/album at a time. In most Windows' forms, I can do multiple individual selections by holding down the CTRL key on each click, or holding down SHIFT to select everything in a range. Would it be possible to implement those?

**Comment by thelucifermorningstar** [comment]
Hello, 
1. It's impossible to open only one command window because the SMLoadr do not allow to send more than a command per window. 
3. I'll try to add this
4.  I'll try to add this.
Thanks :)

**Comment by bascurtiz** [comment]
@camartinez1229 
1. & 2. not possible on AUX' end.
3. Implemented since latest release.
4. By using 3. no need for 4.
