### ISSUE TITLE
Request: Allow to resolve links/artist for full Album list

### ISSUE THREAD

**Issue by theelectricsoul** [thelucifermorningstar/SMLoadr-AUX#2]
Some Artist have a big number of albums. Like so
https://www.deezer.com/de/artist/71513

Would be wonderful if your app could list all of them, by either accepting a link or listing all albums for a picked chosen artist. The chosen artist is to be found when using the "Artist" search option.

Thank you :)

**Comment by thelucifermorningstar** [comment]
good. I'll add this

**Comment by thelucifermorningstar** [comment]
Update is coming! Double click on artist to see all albums, and double click on album to show all tracks!

**Comment by theelectricsoul** [comment]
I am watching the rss feed. Won't miss a thing. :) Thanks
