### ISSUE TITLE
All the characters in all the text boxes are shifted by 2

### ISSUE THREAD

**Issue by Luigigimmi** [thelucifermorningstar/SMLoadr-AUX#20]
![image](https://user-images.githubusercontent.com/8971519/39535326-e297cd56-4e33-11e8-8b8b-489d352277fd.png)
The settings page has the same problem. 
If I digit 'a' the character that appear is 'c' so: 'a' + 2 = 'c'

**Comment by cyckl** [comment]
Same issue here.

**Comment by bascurtiz** [comment]
@Luigigimmi 
@cyckl 
Fixed since v1.0.3.
