### ISSUE TITLE
[Issue] Windows prompt for selecting SMloadr executable doesn't appear.

### ISSUE THREAD

**Issue by ghost** [thelucifermorningstar/SMLoadr-AUX#24]
I'm using Windows 10 Pro (1803) x64. I tried to run it as admin, w7 compatibility but nothing works. Maybe I've to install something else?.

**Comment by WikiCopter** [comment]
Same issue is appearing for me. Was working great until a couple of days ago when the app just stopped launching.

**Comment by ghost** [comment]
Isn't working for me yet, same problem as previous version.

**Comment by bascurtiz** [comment]
@Premium4Free 
@WikiCopter 
How's that working out in v1.0.5?

**Comment by ghost** [comment]
@bascurtiz 
It's working now, I had to activate Windows Media Player. Problem solved.

![captura-1](https://user-images.githubusercontent.com/39070725/42424605-59583bf2-82e5-11e8-8a14-29583856066c.png)

**Comment by WikiCopter** [comment]
It's working, I just installed the next version. I already had WMP activated so that wasn't the issue for me.
________________________________
