### ISSUE TITLE
Debug Log

### ISSUE THREAD

**Issue by ghost** [thelucifermorningstar/SMLoadr-AUX#25]
Hello there,

it would be nice to have some kind of Debug log when the program starts and is running. I can't even use SMLoadr AUX because instantly at the start of the program it goes down and Windows just says it stopped working.

Without any kind of logs it is very hard to debug what the issue is.

Running Windows 10 Enterprise 1607 LTSB, have all MS VisualC++ Redist from 2005 til 2017 and am on NET Framework 4.7.1.

A friend for whom I installed SMLoadr with SMLoad AUX can use the app just fine but he's running annoying Windows 10 Home Edition with automatic updates and obviously has a new Windows 10 version this way.

**Comment by bascurtiz** [comment]
@hidden-refuge 
Try v1.0.5.
