### ISSUE TITLE
Update is coming!

### ISSUE THREAD

**Issue by thelucifermorningstar** [thelucifermorningstar/SMLoadr-AUX#26]

**Comment by bascurtiz** [comment]
Hows the update doing so far?

**Comment by thelucifermorningstar** [comment]
This software will no longer update. :(. but you can update it 
https://mega.nz/#!iXIQ2KyB!ETWBmxK_uJfIP1j8R5c-fPCqYg_F4lp4ozOecAerD14
The Full Project to Visual Studio 2017
Thanks. 
(This project will be deleted soon)

**Comment by bascurtiz** [comment]
D/led it, thanks.
I have Visual Studio installed.
Opened the project file 'SMLoader.csproj'.

I want to give it a try to edit the GUI to my last suggestion here:
https://github.com/thelucifermorningstar/SMLoadr-AUX/issues/4#issuecomment-385350777

I was hoping for a Form/representation of the GUI, to view and edit in Visual Studio,
but so far I only see code.

Can you give me a clue where to start, when I want to edit the GUI/buttons,shape,size,location?

**Comment by thelucifermorningstar** [comment]
in Solution Explorer double click in Form1.cs
To edit shap/size/etc right click and click in propriety and will appear a window to edit.

**Comment by bascurtiz** [comment]
Thanks!
I've got the Search tab almost ready, see:
https://youtu.be/K32fDOu2l4A

2 questions:
~~1) Where do I click in order to view/edit the Settings tab too?~~ Found it!
2) Why isnt the radio-button ''walking along'' showing whether it's showing Artist, Album or Track active?

**Comment by bascurtiz** [comment]
Search+Settings tab ready too now:
https://youtu.be/XK75rBoJQ1g

Can you help me out with the radio-button getting interactive?

**Comment by bascurtiz** [comment]
@thelucifermorningstar 
No need, fixed in v1.0.5!
