### ISSUE TITLE
GUI doesnt download files while CLIdoes

### ISSUE THREAD

**Issue by gatosardina** [thelucifermorningstar/SMLoadr-AUX#27]
Whenever I click to download anything (artist, album or song), a windows cmd prompt opens with SMloadr executing, but then it instantly closes.
I don't have this problem running just SMloadr

no links are added to the GUI folder downloadlinks.txt which I'm guessing could be the culprit
im running both SMloadr AUX and SMloadr as admin and am using latest version on both

**Comment by Neodymium5312** [comment]
Did you open the smloadr interface and login first before trying smloadr gui? I actually made this mistake myself when updating to a new version

**Comment by gatosardina** [comment]
yeah
also, I deleted the whole folder with smloadr and smloadraux and all the files, re-extracted the rar, ran smloadr and downloaded a song, then tried smloadraux and the same thing happened
the smloadr log file in the gui folder is empty too

**Comment by injury99** [comment]
I had similar symptom with the gui launching a cmd window and closing, turns out it didn't like having a space in the name of the download folder.

**Comment by Neodymium5312** [comment]
Wouldn't parsing the commands from the gui to the CLI as a string in "" fix an issue such as this?

**Comment by gatosardina** [comment]
there arent any spaces in the path
the smloadr exe is in a folder in the downloads folder, and smloadr-aux is in a folder indide that
i also tried putting smloadr exe in the same folder as smloadr aux to no avail
also the folder it downloads songs to is called just downloads

**Comment by bascurtiz** [comment]
@gatosardina 
Fixed in v1.0.5!
