### ISSUE TITLE
The new version SMloader 1.0.3 doesnt download the songs bro:(

### ISSUE THREAD

**Issue by eleqful** [thelucifermorningstar/SMLoadr-AUX#28]
the new version 1.03 updated at 18/06/2018 doesnt download the songs pls update :( i think you dont up a file in the zip, the file smloader pls bro update soon :(

**Comment by ElvisTekencio** [comment]
Yep, doesn't work, always opens a new GUI.
Edit: even the past version won't download, what's happening?

**Comment by eraser-head** [comment]
same here

**Comment by ElvisTekencio** [comment]
Ok, erase everything but the smloader executable and the music folder(in case is inside the smloader folder)
then login again in the smloader executable, then copy all the files of the new version to the smloader folder to the executable folder and start the GUI, a new window should prompt asking for the smloader executable location, and should work.

**Comment by eraser-head** [comment]
didn't work for me, same problem. It's weird, but don't know why SMLoadr Aux remember my preferences if it's just a binary. I delete all SMLoadr Aux files downloaded and extracted files in my computer, extract a new ones in diferent folder, and there is the previous configuration.

**Comment by eraser-head** [comment]
with the new update is working perfectly again
