### ISSUE TITLE
New Version 1.0.4 breaks download to volume root

### ISSUE THREAD

**Issue by ClemaX** [thelucifermorningstar/SMLoadr-AUX#29]
When selecting the root of a mounted volume, SMLoadr AUX will set the path to something like `"M:\\\"`, which breaks SMLoadr due to the extra backslash.

**Comment by bascurtiz** [comment]
@ClemaX 
Fixed in v1.0.5!

**Comment by ClemaX** [comment]
Thanks, works for me!
