### ISSUE TITLE
Request: Allow sorting :)

### ISSUE THREAD

**Issue by theelectricsoul** [thelucifermorningstar/SMLoadr-AUX#3]
Some artists have a big amount of entries. Sorting those would be a bliss :)

**Comment by thelucifermorningstar** [comment]
Ok. I'm will work  on it. cheers :)

**Comment by thelucifermorningstar** [comment]
Can you give me a example with a pic? Or just explain more?

**Comment by theelectricsoul** [comment]
https://streamable.com/4a3lp

Of couse being able to sort by album release date would be comfy too ;)

**Comment by thelucifermorningstar** [comment]
ok, I'm working now

**Comment by camartinez1229** [comment]
I would love to see an option to sort listings, such as alphabetically and by release date.

**Comment by thelucifermorningstar** [comment]
@theelectricsoul @camartinez1229 
Added sorting feature in v1.0.6.
