### ISSUE TITLE
Results not showing

### ISSUE THREAD

**Issue by Ashish0804** [thelucifermorningstar/SMLoadr-AUX#32]
these are my settings:
![screenshot 1](https://user-images.githubusercontent.com/39122144/43187345-a7fd97d6-8fe0-11e8-9921-238948e0a1fa.png)
this is the main loading screen which shows fine:
![screenshot 3](https://user-images.githubusercontent.com/39122144/43187376-bc0119e2-8fe0-11e8-87de-fcd226b8dbca.png)
As i click on any artist (Imagine Dragons in this case) nothing shows up, but their cover dos loads up(i have checked my firewall and SML is allowed (gui and aux):
![screenshot 4](https://user-images.githubusercontent.com/39122144/43187423-e09b6e1a-8fe0-11e8-81d0-54534cca33ff.png)
Search results also doesn't show up:
![screenshot 5](https://user-images.githubusercontent.com/39122144/43187439-ec583f80-8fe0-11e8-8cec-c92a2b5126c2.png)
Can u rectify my issue?
Thanks

**Comment by bascurtiz** [comment]
@Ashish0804 
Try a VPN 1st.
I can't replicate this issue.
Try to set your screen text-scaling to 100%.

**Comment by Ashish0804** [comment]
thanks it worked by using a VPN.
