### ISSUE TITLE
Log In Clarification

### ISSUE THREAD

**Issue by Lollausen** [thelucifermorningstar/SMLoadr-AUX#33]
Am I meant to have Deezer Premium/Hifi for this to work? I have a basic account. When using the SMLoadr executable and it asks me for the login (we're talking the cmd-like window, not GUI), it says the credentials are incorrect (I know for a fact they are not, triple checked by logging in and out of Deezer).

**Comment by Loumier** [comment]
It should work with a basic account, you don't need a Premium account.

**Comment by yopcare** [comment]
Same problem here : was working 4 days ago and today can't join...
->  Wrong Deezer credentials
It works when i log into deezer website

**Comment by iemm96** [comment]
Same problem, what happened?

**Comment by yopcare** [comment]
Wrong Deezer credentials...

**Comment by SugnaBB** [comment]
Yeppers i've got the problem as well. I mad another account, still didnt work, reset my passwords, dosent work. I think SMloadr is dead

**Comment by JuniorDjjr** [comment]
Same problem here.

**Comment by Neodymium5312** [comment]
The deezer API has changed. There's a fox but not for smloadr only for deezloader

**Comment by Neodymium5312** [comment]
Newer versions should fix the login issue.

https://git.fuwafuwa.moe/SMLoadrDev/SMLoadr/releases

**Comment by Neodymium5312** [comment]
If the repo above goes down you can always find news and updates for smloadr at the official Telegram channel here: https://t.me/SMLoadrNews

You'll need the telegram application or plugin installed to open a t.me link.
You can find it here: https://telegram.org
