### ISSUE TITLE
SMLoadr link doesn't work

### ISSUE THREAD

**Issue by kannibleklown** [thelucifermorningstar/SMLoadr-AUX#34]
Where can I download it?

**Comment by Loumier** [comment]
https://github.com/thelucifermorningstar/SMLoadr-AUX/releases

**Comment by kannibleklown** [comment]
Not smloadr aux, the program this is for. The link under the description to it no longer works

**Comment by SugnaBB** [comment]
The link has been deleted. I think they must have deleted it all because they got caught for copyright or something... RIP

**Comment by Neodymium5312** [comment]
https://www.google.com/amp/s/amp.reddit.com/r/Piracy/comments/91qv7i/seems_like_smloadr_source_got_taken_down/

**Comment by Neodymium5312** [comment]
Deezer has changed their API as well as the smloadr code was taken down for dmca most likely. There is a source link posted at the address I provided on that Reddit thread. As well as deezerloader is currently working with a fix

**Comment by FatKiwi** [comment]
It's back where it was.

**Comment by Neodymium5312** [comment]
it was taken down again, here is the link to the fixed login version  before it was taken down, got this from waybackmachine. https://web.archive.org/web/20180728150955/https://git.teknik.io/SMLoadrDev/SMLoadr/releases

**Comment by JaineDee** [comment]
Neodymium5312 ....Thanks......Still not able to login to Deezer to activate though.

**Comment by Neodymium5312** [comment]
Its working fine for me. Im using latest 1.9.3 and downloaded multiple albums a few hours ago

**Comment by JaineDee** [comment]
It opens fine, and I can put my user name in for Deezer, but it wont let me
type my password, so nothing happens after that I have to close it down.
Any suggestions?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by JaineDee** [comment]
I've just emptied the cache, and tried again....It's now allowing me to
complete the sign in procedure, and I can download :) ..... Bless you for
that link, and for responding  Neodymium5312

**Comment by yopcare** [comment]
Thx, it works !

**Comment by JaineDee** [comment]
It's stopped working again for me...Now telling me I need to update to the
latest version, and taking me straight to the 404 error page...I really
don't understand what's going on, I've just been using it, clicked it back
on, and now back to square one again :( Im using v1.9.3

**Comment by Neodymium5312** [comment]
Smloadr is updated to 194. Just follow the telegram for latest news and updates

**Comment by JaineDee** [comment]
Where do I find that?.....I'm a new member, so please excuse my ignorance.

**Comment by Neodymium5312** [comment]
https://t.me/SMLoadrNews

**Comment by JaineDee** [comment]
Thanks for your help Neodymium5312, but opera is unable to open the links
inside Telegram since no application associated with tg protocol was found
on my system.

**Comment by Neodymium5312** [comment]
Because it's a Telegram link. You need the telegram application or plugin installed. 

You can find it here. https://telegram.org


Here is the official new repo link. Which I found on their telegram. https://git.fuwafuwa.moe/SMLoadrDev/SMLoadr/releases

I didn't post this in the first place, because their repos keep being DMCA'd and it probably won't be good for long. 

Like I said the best way to get news and updates is to download the telegram application and check the @Smloadrnews channel (which is found at the link I sent earlier) since that won't be taken down.

**Comment by JaineDee** [comment]
Cheers for that, I'm onto it.
