### ISSUE TITLE
Request: Webinterface

### ISSUE THREAD

**Issue by Knocks83** [thelucifermorningstar/SMLoadr-AUX#35]
Hi!
I'd like to have a webinterface so i can put SMloadr on a server and download songs from it.
It would also be easier to download songs on Android.

**Comment by msebastian100** [comment]
Hello,
Yes, a web interface would be a very nice idea

Greetings Sebastian

**Comment by bascurtiz** [comment]
@Knocks83 
@msebastian100 
Won't do.
