### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by luucasalves** [thelucifermorningstar/SMLoadr-AUX#36]
how i can run it on linux?? can use wine?? whats language is based on?

**Comment by bascurtiz** [comment]
You could try using WINE.
C#.

**Comment by titooo7** [comment]
I'd be great to be able to use it in Linux from the command line (so I can use it on my server)

**Comment by Neodymium5312** [comment]
smloadr already supports command line, your on the wrong dev thread, this is for the gui, the application itself supports certain CLI options, its listed on the main page here: https://git.fuwafuwa.moe/SMLoadrDev/SMLoadr

**Comment by Neodymium5312** [comment]
Theres also linux builds released
