### ISSUE TITLE
Allow manual resizing

### ISSUE THREAD

**Issue by theelectricsoul** [thelucifermorningstar/SMLoadr-AUX#37]
![image](https://user-images.githubusercontent.com/10260832/44618627-f170a280-a879-11e8-8aeb-2c54cd96e824.png)

Because I cannot see everything :)

**Comment by theelectricsoul** [comment]
![Need space :)](https://i.imgur.com/Gv2SLmx.png)

**Comment by thelucifermorningstar** [comment]
@theelectricsoul Manual resizing, I haven't been able to make it so. However, the GUI is larger overall since v1.0.6.
