### ISSUE TITLE
1.9.4 does not allow me to log in

### ISSUE THREAD

**Issue by harks12** [thelucifermorningstar/SMLoadr-AUX#39]
I just opened SMLOADR and it asked me to sign in into my deezer account, so i did and when i did everything it says wrong credentials but they are 
<img width="573" alt="Screen Shot 2019-03-08 at 19 30 25" src="https://user-images.githubusercontent.com/48365368/54051025-af38fe00-41d8-11e9-8900-33cc3829de65.png">
right.

**Comment by chudward1234** [comment]
im also having this issue

**Comment by yopcare** [comment]
> 
> 
> im also having this issue

same here :-)

**Comment by Neodymium5312** [comment]
Has anyone tried creating a new account yet? Either Deezer has banned the accounts or they are detecting and blocking smloadr somehow

**Comment by msebastian100** [comment]
Hello,
SMLoadr Not recognized by Deezer.
Deezer Has no detection for these programs
For login problems Please download the current version
SMLoadr-1.9.5

Link: https://git.fuwafuwa.moe/SMLoadrDev/SMLoadr/releases

greetings Sebastian
