### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by bascurtiz** [thelucifermorningstar/SMLoadr-AUX#4]
How about giving SMLoadr-AUX more of a face?

Like this:
![smloadraux-gui-main-v1](https://user-images.githubusercontent.com/34075088/37898935-636a2422-30ea-11e8-88cb-34ee2f302dd6.png)

Or this:
![smloadraux-gui-main-v2](https://user-images.githubusercontent.com/34075088/37898946-696dd1d4-30ea-11e8-8ace-2f833c65c457.png)

**Comment by bascurtiz** [comment]
Or...
![smloadraux-gui-main-v3](https://user-images.githubusercontent.com/34075088/37899335-8d71ef74-30eb-11e8-9159-a29c731a7d20.png)

![smloadraux-gui-main-v4](https://user-images.githubusercontent.com/34075088/37899351-96e901e6-30eb-11e8-9ab7-0ef26139801d.png)

**Comment by thelucifermorningstar** [comment]
Hi. Very nice UI. I'm developing a new UI  to the upcoming version, but i need a feedback: the new UI or 
or the ones you sent me. What's the best? ![UI](https://imgur.com/3I8Ijp1.png)
I'm not good with design, so, help me :)

**Comment by thelucifermorningstar** [comment]
and sorry my bad english :)

**Comment by bascurtiz** [comment]
@thelucifermorningstar 
In the SMLoadr community, many asked for a dark themed color. 
And since that's trending atm, let's go dark =)
Since we're loving D**z*r, I've been heavily inspired by their style.
In the vibe of less = more, I tried to maintain the icon approach,
you already were working on in your last attempt.

Check it out:
![smloadraux-gui-main-v5](https://user-images.githubusercontent.com/34075088/37930271-90118f30-3142-11e8-8994-c4ff2bec6a9b.png)

I can give u the icons I've made in any format.
Which format do you want? SVG/EPS, PNG or ICO?

Colors used:
![smloadr-aux-gui-colors-used](https://user-images.githubusercontent.com/34075088/37931031-b2718358-3144-11e8-9afc-ecc947fa5050.png)

Font used:
Roboto Regular & Bold (just like D**z*r does)
[roboto.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1849427/roboto.zip)


Altered logo:
![smloadraux-logo](https://user-images.githubusercontent.com/34075088/37931125-f2878712-3144-11e8-8e35-c19d048ec68f.png)

**Comment by thelucifermorningstar** [comment]
I'll put this in the next update, next week. PNG Icons please

**Comment by thelucifermorningstar** [comment]
I'll start to work on this UI today

**Comment by bascurtiz** [comment]
Since u request PNG, we can go PNG all the way instead.
This way we can use 3d-effects.

Normal state would be like this:
![smloadr-aux-gui-v6](https://user-images.githubusercontent.com/34075088/37938806-e933b120-315f-11e8-90ce-bef62c471d3f.png)

If u agree, this is more refined AND possible for u to implement,
I'll work on the hover/active/pressed states.

Lemme know. Thanks!

**Comment by thelucifermorningstar** [comment]
I'm using windows forms application. It's possible do this?

**Comment by thelucifermorningstar** [comment]
![image](https://user-images.githubusercontent.com/37758237/37939840-9068e250-313b-11e8-8195-4948d3b41f0c.png)

This is the actual state of UI. I'm waiting for your icons.

**Comment by bascurtiz** [comment]
@thelucifermorningstar 
I think it's possible using Windows Forms Application, but I will investigate asap.
For now, hereby the icons, see attachment.
[icons.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1850024/icons.zip)

**Comment by bascurtiz** [comment]
@thelucifermorningstar 
Yep, it's possible, see this tutorial:
https://www.youtube.com/watch?v=cZcDP8xN6iQ

I will create those different states for the buttons, radio buttons, etc. asap

**Comment by thelucifermorningstar** [comment]
ok. I'm ready. send the PNG

**Comment by bascurtiz** [comment]
Do these work for you?
See attachment.
If you need others, lemme know.
[3d-icons.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1851564/3d-icons.zip)

Background color used: #1c1c1e

**Comment by thelucifermorningstar** [comment]
![eclipse-1s-200px](https://user-images.githubusercontent.com/37758237/37981931-606afcc0-31c5-11e8-91c4-5323068d7650.gif)
Do you have a gif like this? Compatible with the new GUI style? 

To use on the loading of search results

**Comment by bascurtiz** [comment]
I think that one looks cool already.
Since it’s an eclipse , just like the logo, it will fit perfectly!

**Comment by thelucifermorningstar** [comment]
Can you make a 3d Bar to the top of window? 
![image](https://user-images.githubusercontent.com/37758237/37988560-9755c5d2-31d7-11e8-8ee4-07b2d63b74b0.png)
and close and minimize buttons?
Thanks

**Comment by bascurtiz** [comment]
Sure, see attachment.
[topbar.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1853609/topbar.zip)

**Comment by bascurtiz** [comment]
...and favicon to place in topbar:
[smloadr-aux-favicon.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1853634/smloadr-aux-favicon.zip)

**Comment by bascurtiz** [comment]
Hmmm, somehow details get lost when placed on a dark background, try this version:
[smloadr-aux-favicon-v2.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1853646/smloadr-aux-favicon-v2.zip)

**Comment by thelucifermorningstar** [comment]
![1 0 2](https://user-images.githubusercontent.com/37758237/38005562-91caada4-3217-11e8-96e1-653ad3cdcf96.png)
Looks good?

**Comment by bascurtiz** [comment]
Awesome!
Tiny details:
1) The space between Artist & Album compared to Album & Track is not the same (fixed below).
2) There's alot going on in left top-section: let's center the Artist/Album/Track.
3) Also the Search icon is too small compared to the other icons.
4) Since when clicking (mouse down) in the search field will make the icon blue, the font color should be blue there too, I think.

See example:
![gui-example](https://user-images.githubusercontent.com/34075088/38017451-659104c6-3272-11e8-9a00-81e3d1cd6401.png)

Attached the new Searchbar incl. new search-icons.
[searchbar-v2.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1855113/searchbar-v2.zip)

**Comment by thelucifermorningstar** [comment]
Mouse Down
![image](https://user-images.githubusercontent.com/37758237/38030927-6285a6d0-3270-11e8-950c-4e6e63aa1d15.png)

Mouse Up
![image](https://user-images.githubusercontent.com/37758237/38031004-90e905d0-3270-11e8-8423-e5f8ef1e0b6d.png)

**Comment by bascurtiz** [comment]
Great!
Can you give me a test version?
I wanna see how it all interacts.
Willing to work on settings section too.

**Comment by thelucifermorningstar** [comment]
[SMA_1.0.2_Test.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1856225/SMA_1.0.2_Test.zip)

**Comment by bascurtiz** [comment]
All good!

Except the way the play-button works... In your earlier version, SMA 1.0,
You just had to select a track, click ''Preview track'' and it was playing.
Then when clicked a different track, you could instantly click ''Preview track'' and it was playing.
I liked that way of interaction.

In SMA 1.0.2, you first have to disable play before it lets you play a different track :/
Can you revert that back to the way SMA 1.0 does it please?

I noticed you are using the user-icon instead of logo. Good choice!
Since it wasn't really crisp (saw some pixels) I've vectorized it + converted back to PNG.
See 'empty-cover-v2.png' in the attachment.

I've changed some stuff in the Settings, so it looks better.

Check it out:
![gui-settings-example](https://user-images.githubusercontent.com/34075088/38040455-da7ab006-32af-11e8-903b-77f63c169ed3.png)

[gui-settings.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1856681/gui-settings.zip)

**Comment by thelucifermorningstar** [comment]
![image](https://user-images.githubusercontent.com/37758237/38045704-edf3aea6-3293-11e8-8101-d648eeea08e0.png)
[SMA_1.0.2_Test2.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1857008/SMA_1.0.2_Test2.zip)


Play button fixed

**Comment by bascurtiz** [comment]
Looks finished.
Release worthy, if u ask me =)

Only thing I notice is, when u Search for Artist, then switch to Album, then hit Back-button I get an error.
Index out of boundaries. Parametername: index.

**Comment by bascurtiz** [comment]
Oh, and when hitting the Search icon itself (instead of ENTER) the old small Search icon shows up?

**Comment by thelucifermorningstar** [comment]
I will fix this

**Comment by thelucifermorningstar** [comment]
How can I credit you for the help?

**Comment by thelucifermorningstar** [comment]
[SMA_1.0.2_Teste3.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1857937/SMA_1.0.2_Teste3.zip)

**Comment by bascurtiz** [comment]
No need to credit me, happy to help :)

I see you need a disabled back-button in Teste3, so check attach (= more refined).
Mind you, in Test2, the dot of the Album, Artist or Track walked along when u double-clicked for ex.
an Artist, then a specific album, to then show the tracks.
That was really handy.

It's gone in Teste3 now.
Can you revert that back please?

[back-button-disabled.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1858007/back-button-disabled.zip)

**Comment by thelucifermorningstar** [comment]
The double-click function still there. I just separated from the top radio buttons for issue reasons, but I'll find a way to check them again

**Comment by thelucifermorningstar** [comment]
And Thank You so much :)

**Comment by theelectricsoul** [comment]
For the future, I recommend a poll, if making major changes. 

Personally I think, the last and current design is the worst of all. It is hard on the eyes :/ Looking at it hurts after a while. High contrast design, ....   never recommended :) 

The following five have a harmonic contrast. Especially the first 4. If a dark design is preferred, I'd have sticked with number two. Well... just my opinion. :)
![Gui](https://user-images.githubusercontent.com/10260832/38070471-6789419e-331c-11e8-8116-ff15023f72b5.png)

**Comment by theelectricsoul** [comment]
Remember those designs ?   horrible. And I am not trying to be a dick. I am just shocked .. lol. :)

![image](https://user-images.githubusercontent.com/10260832/38070724-b118d454-331d-11e8-9a27-277f82ef8b6b.png)
![image](https://user-images.githubusercontent.com/10260832/38070733-b639664c-331d-11e8-917a-2b0930c95f80.png)

**Comment by bascurtiz** [comment]
@theelectricsoul 
Hmm... Maybe I went a bit too overboard with the dark theme.

How about this?
![smloadr-aux-gui-v7](https://user-images.githubusercontent.com/34075088/38083276-68b1b8ee-3349-11e8-8840-d98a8cc61f4f.png)
![smloadr-aux-gui-settings-v7](https://user-images.githubusercontent.com/34075088/38083279-6ad8218a-3349-11e8-836e-fcaed860d625.png)

**Comment by theelectricsoul** [comment]
The settings menu is much much better. And now I can see the option buttons(artist,album,track) during daylight better. 
Maybe increase brightness on the blue font in the search bar, and it will be good. 

Overall better on my tired eyes :)

**Comment by bascurtiz** [comment]
Alrighty, thanks for feedback. 
Gotta work now, but will make a new package for @thelucifermorningstar asap.

**Comment by bascurtiz** [comment]
@thelucifermorningstar 
Ok, see attachment.
Categorized into Home & Settings folder with all the stuff u need for those.

Notes:

HOME
- Artist/Album/Track font = Roboto-Bold (NOT Black, like u were using) / size = 15pt / color = d0d0d0
- Search font = Roboto-Bold (so it has more contrast with the background) / size = 15pt / color = 0078d7 when active + 6d6d6d when inactive
- Results font = Roboto-Regular / size = 15pt / color = d0d0d0

SETTINGS
- SMLoadr Executable/Downloader Folder/Download Quality font = Roboto-Bold / size = 15pt / color = d0d0d0
- SMLoadr Executable/Download Folder text field font = -Roboto-Regular / size = 15pt / color = 6d6d6d
- Can you change the dropdown font of Quality into Roboto-Regular 15pt too?
- Coded in Hell... font = Roboto-Bold / size = 15pt / color = 6d6d6d
- Set free some... font = Roboto-Regular / size = 15pt / color = d0d0d0

[SMLoadr-GUI-v7.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1861142/SMLoadr-GUI-v7.zip)

- Background color = 333333

**Comment by bascurtiz** [comment]
How cool would this be?
![smloadr-aux-gui-v9](https://user-images.githubusercontent.com/34075088/38145730-1b02af88-344b-11e8-9a6a-f8c81d79e30d.png)

**Comment by theelectricsoul** [comment]
- Looks clean
- well placed objects
- Overall top. Stylish. 

But I personally would light it up a bit. The list box...  could use a little touch of brightness. 

Create a poll and let the SMLoadr community vote on some designs :)

**Comment by bascurtiz** [comment]
Lighted it up a bit + some refinements (like the edges):
![smloadr-aux-gui-v10](https://user-images.githubusercontent.com/34075088/38154545-cafe5280-3472-11e8-8572-0f6836938da6.png)

**Comment by thelucifermorningstar** [comment]
Hi @bascurtiz, sorry for the absence

**Comment by thelucifermorningstar** [comment]
This last GUI is pretty amazing. You're a artist :)

**Comment by theelectricsoul** [comment]
Your design is a "night" design. It allows the details to be seen, only if the background an the room you are sitting in is somehow dark.

My room is bright, and my desktop too. Thats why it is harder for me to see the borders of the textbox. 

It's like with some reading apps on a phone or navigations GPS apps. There are dark themes for dark rooms, and light ones. Dark themes are nice if everything else is dark too. Its good to the eyes. But a bright light in dark surroundings....   that hurt my retine :) , and vica versa :)

But do not worry. The design is truly great.

**Comment by thelucifermorningstar** [comment]
@bascurtiz when you have a defined design, you can send to me

**Comment by thelucifermorningstar** [comment]
About the colors, could have a black and a white theme to select on settings. A white version of this last GUI

**Comment by theelectricsoul** [comment]
that'd be some pro shit :)

**Comment by bascurtiz** [comment]
Like this:
![smloadr-aux-gui-v11](https://user-images.githubusercontent.com/34075088/38164606-78246eec-3507-11e8-96f0-cb5e62f3fe35.png)

**Comment by thelucifermorningstar** [comment]
Yeah. Perfect

**Comment by bascurtiz** [comment]
Ok, I'll create a dark + bright package based on the 2 latest pics asap.

**Comment by thelucifermorningstar** [comment]
ok :)

**Comment by theelectricsoul** [comment]
yeeeeaaa :)

**Comment by theelectricsoul** [comment]
butter to my eyes :)

**Comment by bascurtiz** [comment]
@thelucifermorningstar 
Try out this SMLoadr-GUI-v8-bright Home-section 1st.
Let me know if this works for you.
[SMLoadr-AUX-GUI-v8-bright-Home.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1865664/SMLoadr-AUX-GUI-v8-bright-Home.zip)

**Comment by thelucifermorningstar** [comment]
Works fine

**Comment by bascurtiz** [comment]
Great!
Hereby the dark theme, Home-section.
[SMLoadr-AUX-GUI-v8-dark-Home.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1865887/SMLoadr-AUX-GUI-v8-dark-Home.zip)

**Comment by bascurtiz** [comment]
NOTES:

HOME BRIGHT
- ''Artist/Album/Tracks'' font = Roboto-Bold / size = 12pt / color = 000000
- ''Search'' font = Roboto-Bold / size = 12pt / color = ffffff when active, a6a9b3 when inactive
- ''Results'' font = Roboto-Bold / size = 11pt / color = ffffff

HOME DARK
- ''Artist/Album/Tracks'' font = Roboto-Bold / size = 12pt / color = d0d0d0
- ''Search'' font = Roboto-Bold / size = 12pt / color = 0078d7 when active, d1d1d1 when inactive
- ''Results'' font = Roboto-Bold / size = 11pt / color = ffffff when selected, d0d0d0 when not selected

**Comment by thelucifermorningstar** [comment]
![image](https://user-images.githubusercontent.com/37758237/38168502-3f388d26-3524-11e8-9c79-ca6fab0aa4ed.png)

![image](https://user-images.githubusercontent.com/37758237/38168513-aaae2f3e-3524-11e8-8784-376a2ce4428c.png)

**Comment by bascurtiz** [comment]
Why is your font bigger than mine?
Feels a bit pompous / less refined.

**Comment by theelectricsoul** [comment]
I agree :) less refined.

**Comment by thelucifermorningstar** [comment]
I had to resize the fonts from 12pt to 9 to be exactly to your design
![image](https://user-images.githubusercontent.com/37758237/38168749-c86a6120-352c-11e8-8bce-4fec9b26514b.png)
and the dark buttons are different from your concept

**Comment by bascurtiz** [comment]
Ahh, looks like Photoshop & Visual Studio not using the same value font-size wise. 
Good to know.

Yep I altered the buttons a bit.

Perhaps use 
- ''Results'' = color ffffff when selected, d0d0d0 when not selected

if possible.

Perfect size font-wise now!

**Comment by thelucifermorningstar** [comment]
in listbox it's not possible to change the color for a selected item. you need to change to entire listbox

**Comment by bascurtiz** [comment]
In that case, stick with the d0d0d0 color, I think.
The contrast between the background (blackish) and text (white) is a bit too high using ffffff.

I'm not so fond of the disabled buttons Back + Play, since the screen opens with it (and differ alot).
Hereby v2 of those.

[SMLoadr-AUX-GUI-v8-dark-disabled-v2.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1866226/SMLoadr-AUX-GUI-v8-dark-disabled-v2.zip)

**Comment by bascurtiz** [comment]
Will work on a package for Dark/Settings as shown below asap:

![smloadr-aux-gui-settings-v8-dark](https://user-images.githubusercontent.com/34075088/38171712-816e687a-359f-11e8-8eac-c3c5fd1394ec.png)

**Comment by bascurtiz** [comment]
Hereby the dark theme, Settings-section.
[SMLoadr-AUX-GUI-v8-dark-Settings.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1866237/SMLoadr-AUX-GUI-v8-dark-Settings.zip)

NOTES:

SETTINGS DARK

''SMLoadr Exec, Folder, Quality, Theme'' font = Roboto-Bold / size = 12pt / color = d0d0d0
''in bar'' font = Roboto-Regular / size = 12pt / color = 666666
''Dark/Bright'' font = Roboto-Bold / size = 11pt / color = d0d0d0
''Version'' font = Roboto-Bold / size = 12pt / color = 666666
''Coded in...'' font = Roboto-Bold / size = 12pt / color = d0d0d0
''Set free...'' font = Roboto-Regular / size = 12pt / color = 666666

**Comment by thelucifermorningstar** [comment]
Nice :)

**Comment by bascurtiz** [comment]
Will work on a package for Bright/Settings as shown below asap:
![smloadr-aux-gui-settings-v8-bright](https://user-images.githubusercontent.com/34075088/38193467-7dce7b6e-3672-11e8-9262-3d3cea42a15d.png)

**Comment by bascurtiz** [comment]
Also for Bright theme, I've altered the disabled buttons so they look more like the button-up variant:
[SMLoadr-AUX-GUI-v8-bright-disabled-v2.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1867917/SMLoadr-AUX-GUI-v8-bright-disabled-v2.zip)

**Comment by bascurtiz** [comment]
Hereby the Bright theme, Settings-section.
[SMLoadr-AUX-GUI-v8-bright-Settings.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1867919/SMLoadr-AUX-GUI-v8-bright-Settings.zip)

NOTES:

SETTINGS BRIGHT

''SMLoadr Exec, Folder, Quality, Theme'' font = Roboto-Bold / size = 12pt / color = 000000
''in bar'' font = Roboto-Regular / size = 12pt / color = d0d0d0
''Dark/Bright'' font = Roboto-Bold / size = 11pt / color = 000000
''Version'' font = Roboto-Bold / size = 12pt / color = 666666
''Coded in...'' font = Roboto-Bold / size = 12pt / color = 000000
''Set free...'' font = Roboto-Regular / size = 12pt / color = 666666

**Comment by bascurtiz** [comment]
*Oops, I had the layers below set to 80% transparency, so colors will be more like this for you:

HOME BRIGHT
''Artist/Album/Tracks'' font color = 565653

SETTINGS BRIGHT
''SMLoadr Exec, Folder, Quality, Theme'' font color = 565653
''Dark/Bright'' font color = 565653

**Comment by bascurtiz** [comment]
Wanted to give the buttons a more realistic effect, 
so changing the button-styles for button-up + mouse-over:

![smloadr-aux-gui-settings-v8-dark-button-edit](https://user-images.githubusercontent.com/34075088/38207041-c2c668dc-36ac-11e8-9a5c-4ff92adf35f2.png)

![smloadr-aux-gui-settings-v8-bright-buttons-edit](https://user-images.githubusercontent.com/34075088/38210612-345cab7c-36b8-11e8-85e1-c744c4cac0a2.png)


Whereas
Change is ''button-up'';
Open is ''button-down'';
Reset is ''mouse-over''.

Package for Dark + Bright coming up asap.

**Comment by bascurtiz** [comment]
Dark buttons for Home + Settings attached.
![smloadr-aux-gui-home-v8-dark](https://user-images.githubusercontent.com/34075088/38213569-022145be-36c2-11e8-89c4-6966ccb9425a.png)


&

Bright buttons for Home + Settings attached.
![smloadr-aux-gui-home-v8-bright](https://user-images.githubusercontent.com/34075088/38213634-51760ce4-36c2-11e8-886d-6e5a28bd3c6f.png)



[SMLoadr-AUX-GUI-v8-dark-Buttons-v2.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1868986/SMLoadr-AUX-GUI-v8-dark-Buttons-v2.zip)
[SMLoadr-AUX-GUI-v8-bright-Buttons-v2.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1868996/SMLoadr-AUX-GUI-v8-bright-Buttons-v2.zip)

**Comment by thelucifermorningstar** [comment]
:)

**Comment by thelucifermorningstar** [comment]
New update with the new GUI next month. I'm without internet connection to work now.

**Comment by theelectricsoul** [comment]
sweet

**Comment by bascurtiz** [comment]
@thelucifermorningstar 
@theelectricsoul 
Perhaps I should do a re-edit, since #7 will defo be an issue with this latest design.
Also, most screens people use nowadays are 16:9.
So I'm thinking to shape it into that same ratio: This way the results-field/box can be wider by default.
What you guys think?

**Comment by bascurtiz** [comment]
Mimicked the GUI of Deezer's Xbox One interface, which happens to be also 16:9 ratio.
Looks clean and simple, and if u ask me, no need for bright or dark theme, due the bigger font.

![smloadr-aux-gui-home-v10-dark-flat](https://user-images.githubusercontent.com/34075088/38769196-170c9d84-3fff-11e8-93e8-c2200cedbe00.png)
![smloadr-aux-gui-settings-v10-dark-flat](https://user-images.githubusercontent.com/34075088/38769197-1724d9f8-3fff-11e8-9f83-033bebc02aba.png)

NOTES:
Background color = #1a1922

___

SEARCH NOTES:

Search/Settings
- font = Roboto-Regular
- size = 15pt
- color = #1976d2 when active, #c2c2ca when not-active, #fbfaff when mouse-over

Search text (big)
- font = Roboto-Regular
- size = 30pt
- color = #fbfaff

Artist/Album/Track/Playlist/URL 
- font = Roboto-Regular
- size = 17pt
- color = #1976d2 when active, #c2c2ca when not-active, #fbfaff when mouse-over

Limit Results/Back
- font = Roboto-Regular
- size = 15pt
- color = #1976d2 when active, #c2c2ca when not-active, #fbfaff when mouse-over

Search bar
- color = #393941

Search bar text
- font = Roboto-Regular
- size = 17pt
- color = #fbfaff when active, #c2c2ca when not-active

Results background
- color = #23232c

Results selected bar
- color = #1976d2

Results scroll bar
- color = #393941

Results text
- font = Roboto-Regular
- size = 17pt
- color = #c2c2ca

Download/Play
- font = Robot-Regular
- size = 17pt
- color = #1976d2 when active, #c2c2ca when not-active, #fbfaff when mouse-over

___

SETTINGS NOTES:

Search/Settings
- font = Roboto-Regular
- size = 15pt
- color = #1976d2 when active, #c2c2ca when not-active, #fbfaff when mouse-over

Settings text (big)
- font = Roboto-Regular
- size = 30pt
- color = #fbfaff

Coded in Hell...
- font = Roboto-Regular
- size = 13pt
- color =#c2c2ca

Version...
- font = Roboto-Regular
- size = 13pt
- color = #fbfaff

SMLoadr Executable/Download Folder/Download Quality
- font = Roboto-Regular
- size = 17pt
- color = #5d5c65

SMLoadr Executable/Download Folder background bar
- color = #393941

SMLoadr Executable/Download Folder text
- font = Roboto-Regular
- size = 17pt
- color = #c2c2ca

Download Quality text/Auto Shutdown SMLoadr/Change/Open text
- font = Robot-Regular
- size = 17pt
- color = #1976d2 when active, #c2c2ca when not-active, #fbfaff when mouse-over

Please consider to donate
- font = Robot-Regular
- size = 13pt
- color = #fbfaff

Copy Bitcoin/Ethereum/Monero address text
- font = Robot-Regular
- size = 13pt
- color = #1976d2 when active, #c2c2ca when not-active, #fbfaff when mouse-over

When some function is disabled
- color = #5d5c65
___

Attached a lil package with logo's + search & results background fills + scrollbar & minimize+close.
[SMLoadr-AUX-GUI-v10.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1910514/SMLoadr-AUX-GUI-v10.zip)

**Comment by theelectricsoul** [comment]
I think the other designs are...  clean :) ....    its like comparing a gamer case for computers to "Lian Li" cases. But yes.... 16:9 is very welcome :)

**Comment by thelucifermorningstar** [comment]
I'm back to work guys

**Comment by bascurtiz** [comment]
@thelucifermorningstar 
Great!
Esp. since SMLoadr v2 (incl. GUI) prolly will never be released.

**Comment by theelectricsoul** [comment]
Get your ass back to work ;)  lol.

**Comment by bascurtiz** [comment]
@thelucifermorningstar 
Any progress yet?

I've changed some minor things on the bottom of both sections:
![smloadr-aux-gui-home-v10-dark-flat-v2](https://user-images.githubusercontent.com/34075088/39421541-d2679acc-4c69-11e8-832b-b40f6703dfd4.png)
(Download + Play in the middle of the empty space below, so it gets a more solid feeling)

![smloadr-aux-gui-settings-v10-dark-flat-v2](https://user-images.githubusercontent.com/34075088/39421427-4a13deb0-4c69-11e8-8e15-d66f32da96f1.png)
(Donate text + bitcoin logo's next to eachother, so it doesnt feel like its falling off)

**Comment by thelucifermorningstar** [comment]
Hi. 21:00 UTC I'll show the progress.
