### ISSUE TITLE
Possible Request(s)

### ISSUE THREAD

**Issue by Gamer4Life2020** [thelucifermorningstar/SMLoadr-AUX#41]
No biggie, but would it be possible to get tracks from other country as an alternative like Deezer RMX? I like this program more as it simpler and more friendly and has the tags I need for Picard without having to search or manually enter them. Lastly if possible it would be nice to have the album link in the source and not just Deezer as a reference, but Deezer if better than nothing. 

Or would this be something I would need to ask the Dev. of SM-loader?

Thanks for the awesome program.

**Comment by thelucifermorningstar** [comment]
AFAIK, Remix doesn't get tracks from other countries. 
I think you are confused.
You can however just use the google trick, like: artist - title :deezer.com and it could possibly show other results (from other countries) than the one in your ip/country.

Those links you are still able to download, by copy/pasting them into AUX, using the URL-mode.

Album link in the source?
You mean writing the url-link into the tags somewhere like idk, which tag, you want to give up for...
You should ask SMLoadr Dev.

You're welcome.
