### ISSUE TITLE
View/Edit downloadLinks.txt within the application

### ISSUE THREAD

**Issue by azumukupoe** [thelucifermorningstar/SMLoadr-AUX#42]

**Comment by thelucifermorningstar** [comment]
@azumukupoe

Like this?
https://i.imgur.com/9Ax7t5B.mp4

**Comment by azumukupoe** [comment]
@thelucifermorningstar 

Yes something like that but I'd like to be able to check the titles among the urls if that's possible.

**Comment by thelucifermorningstar** [comment]
@azumukupoe

View/Edit downloadLinks.txt within the application, you requested.
What your asking now is totally different ballgame. 
And won't do.
