### ISSUE TITLE
Problem "Download downloadLinks.txt"

### ISSUE THREAD

**Issue by frank1995** [thelucifermorningstar/SMLoadr-AUX#43]
Problem when select option "Download downloadLinks.txt" when app just started and no search made

![Screenshot_1](https://user-images.githubusercontent.com/12147291/74110879-b3426e00-4b55-11ea-9cbc-875d2fa942a1.png)
![Screenshot_2](https://user-images.githubusercontent.com/12147291/74110882-b76e8b80-4b55-11ea-9e85-62673f3e3266.png)
![Screenshot_3](https://user-images.githubusercontent.com/12147291/74110884-bb021280-4b55-11ea-8936-bd85bd21ed1c.png)

**Comment by bascurtiz** [comment]
@frank1995
Why select option "Download downloadLinks.txt" when app just started and no search made?
Then there's nothing to download =)

**Comment by frank1995** [comment]
Hi @bascurtiz 
Sorry... my bad, let me explain you...
i have added some links to "downloadLinks.txt", but if you made a search with no results and select the option "Download downloadLinks.txt" the app crash...

days ago i reopened the app and app didn't the initial search... by this reason i wrote with no search made...

now i tried again but with an space " " (a search with no results)
and again... app crash...

here an example...
![Screenshot_1](https://user-images.githubusercontent.com/12147291/74597615-f99d3e80-5027-11ea-9ba9-0ffd8f45fd3f.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/12147291/74597618-fbff9880-5027-11ea-8dde-0b8d197e1fe9.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/12147291/74597622-002bb600-5028-11ea-8173-18fe63dd0bda.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/12147291/74597623-01f57980-5028-11ea-9336-0c60cdb80623.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/12147291/74597624-03bf3d00-5028-11ea-9bdf-fe9be64072c2.jpg)

**Comment by bascurtiz** [comment]
@frank1995 

I can reproduce it, when I search for a '' '' space.
But why would I search for a empty space in the 1st place?

If you just search for a track name or whatever, and add it to downloadlinks.txt , then hit download downloadlinks.txt it works fine.

**Comment by frank1995** [comment]
@bascurtiz 
Man... i just reported a minimal issue... i just thought somebody can solved it... maybe for a future update... :/

i'm not trying to do a problem about it...

i found the problem like always somebody found them... BY MISTAKE
