### ISSUE TITLE
Track search doesn't work

### ISSUE THREAD

**Issue by dxf** [thelucifermorningstar/SMLoadr-AUX#44]
Album, artist work fine but track doesn't. Weird.

Windows 10, 1.10.1

**Comment by Neodymium5312** [comment]
Why not make the switch to deezloader remix? This application was dropped for a long time, the command line isn't being updated regularly and deezloader remix has many more quality of life features and works much better. Find the telegram group for more information. The program is also being rewritten from the ground up under a new name soon. So development is very active on this in comparison to the currently barely working smloader base app that this repo is just a gui for . httpss://notabug.org/RemixDev/deemix

**Comment by bascurtiz** [comment]
@dxf 
Can't replicate this issue.
VPN might do the trick for you.
