### ISSUE TITLE
Issues with SMLoadr AUX.exe

### ISSUE THREAD

**Issue by Zuru32** [thelucifermorningstar/SMLoadr-AUX#45]
Dear Support :)
I have an issue with the Exe (Version 1.10.1.0). The exe starts normal but then I can only see part of the whole Exe. I can not close or hide the window. See the attached screenshot:

![Unbenannt](https://user-images.githubusercontent.com/63952778/79684820-9781d500-8234-11ea-9fa9-45a11145ea4a.PNG)

The second issue I have is with the settings in the Exe. I can't change the path and download folder. Again I attached a screenshot:

![Smloadr Settings](https://user-images.githubusercontent.com/63952778/79684993-b5036e80-8235-11ea-9d55-b38598718161.PNG)

Would be great to hear from you :) Thank you so much for providing us with this amazing App to enjoy free music 👍

**Comment by bascurtiz** [comment]
@Zuru32 
Make sure you have a minimum resolution of 1280x800 at 100% scale.

**Comment by thelucifermorningstar** [comment]
@Zuru32

For those that have a low-resolution screen, try this alternative updated version attached.
[SMLoadr AUX-lowres.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/4634930/SMLoadr.AUX-lowres.zip)

**Comment by Zuru32** [comment]
Thanks a lot for the help and the updated version :-) It works!!!
