### ISSUE TITLE
Only 6 songs loaded in flac if you select all albums of one artist. 

### ISSUE THREAD

**Issue by viper2020dr** [thelucifermorningstar/SMLoadr-AUX#46]
Many, many thanks for the update today!

But there is one issue since a few days: Only 6 songs of each album will be loaded in flac if you select the artist and click on download then. 

Maybe this could be fixed?

Thank you soooo much!!!

**Comment by spaz155** [comment]
This seems to happen regardless of the format. Please fix!

**Comment by bascurtiz** [comment]
@viper2020dr 
@spaz155 
Fixed in latest release v1.23 here: https://git.fuwafuwa.moe/SMLoadrDev/SMLoadr/releases
