### ISSUE TITLE
Change download folder structure?

### ISSUE THREAD

**Issue by turbodude** [thelucifermorningstar/SMLoadr-AUX#47]
Hi, how do I change the path where files are saved? I tried editing SMLoadrConfig and setting
"albumName" to "%artist% - %album% (%year%)" and
"fileName" to "%artist% - %title%"
but the app is saving to "%album% (%type%)" and "%number% %title%" anyways.

**Comment by bascurtiz** [comment]
@turbodude 
Not possible anymore since 2020.
