### ISSUE TITLE
Only download in MP3 128 kbs

### ISSUE THREAD

**Issue by Debop22** [thelucifermorningstar/SMLoadr-AUX#48]
hello,my name is Ton and i am new here.
Till a few days ago the program worked fantastic.Then when I tried to download an album it only did 6 or 7 songs of an album.By repeating I could manage to download the whole album.
Since two days I can only download in MP3 128 KbS.
Can somebody help me out on this issue.
Thanks in advance

**Comment by bascurtiz** [comment]
@Debop22 
Fixed since v1.22.
Grab the latest here: https://git.fuwafuwa.moe/SMLoadrDev/SMLoadr/releases
