### ISSUE TITLE
Search by label and filter/sort by release date

### ISSUE THREAD

**Issue by andrewate** [thelucifermorningstar/SMLoadr-AUX#49]
Hi, what a great project, I've been using it for a year now, thanks a lot! There is one thing that would be helpful, but not sure if possible: one may look for albums released by a specific label by putting in the search query -- label:"your_label_here" -- without dashes . Is it possible to narrow down your search by or sort by a year of album release? Deezer presents maximum 300 albums in an arbitrary order, and the newest may be out of reach or you just don't know for sure which are newest. You provide release date sorting option when presenting albums of a specific artist - so doing the same for labels would be just fantastic! Thank you.

**Comment by thelucifermorningstar** [comment]
@andrewate 
Great idea!
But too much hassle and a shitload of extra calls to be made... not risking that investment.
