### ISSUE TITLE
Release 1.0.2 is missing the binaries :)

### ISSUE THREAD

**Issue by theelectricsoul** [thelucifermorningstar/SMLoadr-AUX#5]

**Comment by thelucifermorningstar** [comment]
It was a test to automatic version cheker in porgram. I don't know how delete

**Comment by theelectricsoul** [comment]
https://help.github.com/articles/editing-and-deleting-releases/

**Comment by thelucifermorningstar** [comment]
Thank you :)

**Comment by thelucifermorningstar** [comment]
![image](https://user-images.githubusercontent.com/37758237/37928150-423e0db8-3112-11e8-873e-f9350725ccd2.png)
No edit button :(

**Comment by theelectricsoul** [comment]
damn :)   Sure its your account ;)

**Comment by theelectricsoul** [comment]
Noticed this line ?
Tip: You must delete all binary files attached to a release before you can delete the release.

**Comment by thelucifermorningstar** [comment]
Solved :)

**Comment by thelucifermorningstar** [comment]
Thanks
