### ISSUE TITLE
6 Song issue when selecting all albums of an artist is back

### ISSUE THREAD

**Issue by viper2020dr** [thelucifermorningstar/SMLoadr-AUX#50]
Hi Lucifer,

the 6 Song issue is back you when select all albums of an artist. Only the first 6 songs of each album will be loaded unfortunately.

**Comment by thelucifermorningstar** [comment]
@viper2020dr 
I can't reproduce it.
Just d/led (in FLAC) an artist using AUX while searched up the artist name. then hit the d/l button.
Now i see albums and singles, while some albums contain 14 tracks and 31 tracks for ex.
Are you sure you've updated to SMLoadr 1.23?
