### ISSUE TITLE
Maximum allowed entries do not work

### ISSUE THREAD

**Issue by theelectricsoul** [thelucifermorningstar/SMLoadr-AUX#6]
[Check the video :)](https://streamable.com/dlrae)

Thank you for the update. I tested the x64 Version.

**Comment by thelucifermorningstar** [comment]
I can see. The maximun results permited by the Deez api is only 100. I'll fix this. So, it's impossible to see more than 100 entries :(

**Comment by bascurtiz** [comment]
@theelectricsoul 
Since v1.0.5 it is set to unlimited (which is 300 in API)
