### ISSUE TITLE
Request: Open webpage link directly

### ISSUE THREAD

**Issue by theelectricsoul** [thelucifermorningstar/SMLoadr-AUX#8]
Hello

I think the primary usage of clicking on the link at the very bottom right should be the direct opening of the website in the systems standard browser, instead of copying the link into the clipboard.

:)

**Comment by thelucifermorningstar** [comment]
Right Click to open the menu
![image](https://user-images.githubusercontent.com/37758237/38031861-9e23904c-3272-11e8-993f-e5b00e91f220.png)
Soon in the next update

**Comment by theelectricsoul** [comment]
sweet
