### ISSUE TITLE
Program crashes immediately on startup.

### ISSUE THREAD

**Issue by camartinez1229** [thelucifermorningstar/SMLoadr-AUX#9]
Hello. I'm using Windows 8.1 x64, and have the SMLoadr-AUX files in the same directory as SMLoadr.exe. However, SMLoader-AUX always crashes on startup. This has happened with 1.0.0 and 1.0.1. If it matters, I have .NET Framework 4.7.1 installed.

Simply double-clicking the EXE, I get a typical "has stopped working" error message. However, if I try to right-click and run the EXE as administrator, I get an error message such as the following:

> 
> .NET-BroadcastEventWindow.4.0.0.0.141b42a.0: SMLoadrAUX_1.0.1_x64.exe - Application Error
> ---------------------------
> The exception unknown software exception (0xe0434352) occurred in the application at location 0x54d292fc.

**Comment by thelucifermorningstar** [comment]
Hello. Try this: 
[SMA_1.0.2_Test.zip](https://github.com/thelucifermorningstar/SMLoadr-AUX/files/1857778/SMA_1.0.2_Test.zip)

**Comment by camartinez1229** [comment]
Thank you for the quick response. However, I'm getting the same exact error.

**Comment by thelucifermorningstar** [comment]
Maybe your Windows or Net Framework installation is missing files. 
Works on the vast majority of computers. Tested even on Windows 7

**Comment by camartinez1229** [comment]
Well, I haven't had any issues with other programs that use .NET Framework, so, I'm not sure what's going on. I might try reinstalling my .NET Framework later, but that's not something I have the time for right now. Thanks for responding anyway, though.

**Comment by daihakken** [comment]
> Problem signature:
>   Problem Event Name:	CLR20r3
>   Problem Signature 01:	SMLoader.exe
>   Problem Signature 02:	1.0.0.0
>   Problem Signature 03:	5abc5d4f
>   Problem Signature 04:	System.Windows.Forms
>   Problem Signature 05:	4.7.2117.0
>   Problem Signature 06:	59cf5186
>   Problem Signature 07:	60f
>   Problem Signature 08:	36
>   Problem Signature 09:	PSZQOADHX1U5ZAHBHOHGHLDGIY4QIXHX
>   OS Version:	6.1.7601.2.1.0.320.65
>   Locale ID:	3076
>   Additional Information 1:	0a9e
>   Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
>   Additional Information 3:	0a9e
>   Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
> 

I am also experiencing a startup crash, here's the log from Windows 7 error dialog.

**Comment by camartinez1229** [comment]
I finally figured out my issue. I had disabled "Media Features" in Windows Features (Programs and Features -> Turn Windows features on or off), which apparently has some functionality that the program depends on. I figured this out by trial and error in a Windows 7 VM, and then confirmed on my Windows 8.1 install. I figured there had to be something, because the program also worked fine on my parents' laptops, Windows 7 and Windows 10 respectively.

So, after re-enabling Media Features and restarting my laptop, the program now works correctly for me.

**Comment by ghost** [comment]
@camartinez1229 You probably saved my day. Thank you. A debug log would be nice though. @thelucifermorningstar would you mind to add a dependency/requirements list to the readme?

I totally wouldn't have expected that this app would need "Media Features".

**Comment by thelucifermorningstar** [comment]
@hidden-refuge "Media Features" request info will show since v1.0.5.
